### ISSUE TITLE
Not an issue but I couldn't find another way to contact you.

### ISSUE THREAD

**Issue by ctnlaring** [zackthehuman/mm3info#1]
I'm trying to write a megaman playing robot in python. Is there a way I can use your script to put megaman's coordinates in a file or something so I can get to them with python?

**Comment by zackthehuman** [comment]
@Collinthegeek Hmm, well since FCEUX supports scripting via Lua, there should be a way for you to write out the position to a text file while the script is running. 

There is some documentation here: http://www.fceux.com/web/help/fceux.html?LuaScripting.html

However, I don't know if the `io` module is loaded, so you'll have to play around with it and see.

Is it a requirement that you use Python? This script already gives you the ability to control the game either through pretending to pump in controller input or by direct memory manipulation...

**Comment by zackthehuman** [comment]
@Collinthegeek If you want to contact me personally you send electronic mail to the address version of "zack at zack the human dot com". I'm interested in your Mega Man-playing robot project :)
